_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.95
block_size:
    value: 1024
checkpoint_dir:
    value: checkpoints
dataset_dir:
    value: data/enwik8_char
decay_lr:
    value: true
device:
    value: cuda
eval_interval:
    value: 500
eval_iters:
    value: 100
grad_clip:
    value: 1
learning_rate:
    value: 0.0006
log_interval:
    value: 10
lr_decay_iters:
    value: 600000
max_iters:
    value: 600000
min_lr:
    value: 6e-05
model_config:
    value:
        bias: false
        block_size: 1024
        n_embd_a: 512
        n_embd_attention: 512
        n_embd_b: 512
        n_head: 8
        n_layer: 9
        rope_base: 100000
        rope_condense_ratio: 1
        vocab_size: 6064
use_only_a:
    value: false
wandb_log:
    value: true
wandb_project:
    value: mini-gpt-sparse
wandb_run_name:
    value: sparse
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
