_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 1024
compile:
    value: false
dataset:
    value: enwik8_char
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0
dtype:
    value: bfloat16
eval_interval:
    value: 500
eval_iters:
    value: 100
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 2
init_from:
    value: scratch
learning_rate:
    value: 0.0006
log_interval:
    value: 10
lr_decay_iters:
    value: 600000
max_iters:
    value: 600000
min_lr:
    value: 6e-05
n_embd:
    value: 768
n_embd_a:
    value: 512
n_embd_attention:
    value: 512
n_embd_b:
    value: 512
n_head:
    value: 8
n_layer:
    value: 9
out_dir:
    value: out-enwik8-char-sparse
sparse_model:
    value: true
true_mask:
    value: true
wandb_log:
    value: true
wandb_project:
    value: enwik8-char-sparse
wandb_run_name:
    value: mini-gpt-sparse
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
